version: '3'
services:
  nextjs: 
    build: ./
  nginx: 
    build: ./nginx
    ports:
      - 80:80
  postgres:
    container_name: postgres
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: deadfill
      POSTGRES_PASSWORD: filldead18101990
      POSTGRES_DB: electro_db
    volumes:
       - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmintest
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 12fill12@mail.ru
      PGADMIN_DEFAULT_PASSWORD: filldead18101990
    ports:
      - "5050:80"
    networks:
      - postgres
    links:
      - "postgres"
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
