version: '3.9'

services:
  nextjs:
    environment:
    - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-appdb}
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - app_network
  db:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - '8080:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
    depends_on:
      - db
    networks:
      - app_network
  nginx: 
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - nextjs
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge